Login feature
christianahvilla/das-api pull request #2
Opened 2022-05-06 15:41 UTC by PedroAGC

Login and signin features

2022-05-06 17:03 UTC, christianahvilla requested changes
Please check unnecessary comments, add comment when it is necesary, add new line at the of files.

2022-05-06 17:03 UTC, christianahvilla commented on src/controllers/auth.controller.ts
> +        throw new Error('Invalid Credentials');
```suggestion
    if(!user){
        throw new Error('Invalid Credentials');
    }
```

2022-05-06 17:03 UTC, christianahvilla commented on src/controllers/auth.controller.ts
> +        throw new Error('Invalid Credentials');
```suggestion
    if(!validPassword) {
        throw new Error('Invalid Credentials');
     }
```

2022-05-06 17:03 UTC, christianahvilla commented on src/controllers/auth.controller.ts
> +    return data;
```suggestion

    return data;
```

2022-05-06 17:03 UTC, christianahvilla commented on src/controllers/user.controller.ts
> +import User, { UserInput, UserOutput } from '../models/user.model';
```suggestion
import User, { UserInput, UserOutput } from '../models/user.model';
```

2022-05-06 17:03 UTC, christianahvilla commented on src/controllers/user.controller.ts
> +    }
```suggestion
    if(userExists) {
        throw new Error(`The user with the email ${email} is already registered`);
    }
    const phoneExists = await User.findOne({where: {phone: phone}})
    if(phoneExists) {
        throw new Error(`The user with the phone ${phone} is already registered`);
    }
```

2022-05-06 17:03 UTC, christianahvilla commented on src/database/connection.ts
> +export default db;
add new line after end of file

2022-05-06 17:03 UTC, christianahvilla commented on src/helpers/jwtGenerator.ts
> +            }
```suggestion
        }, (err, token) => {
            if(err) {
                console.log(err);
                reject('The ');
            } else {
                resolve(token);
            }
```

2022-05-06 17:03 UTC, christianahvilla commented on src/middlewares/fieldsValidator.ts
> +        return res.status(400).json(errors);
```suggestion
    if (!errors.isEmpty()) {
    
        return res.status(400).json(errors);
    }
```

2022-05-06 17:03 UTC, christianahvilla commented on src/middlewares/fieldsValidator.ts
> +export default fieldsValidation;
```suggestion
export default fieldsValidation;

```

2022-05-06 17:03 UTC, christianahvilla commented on src/models/index.ts
> +
```suggestion

```

2022-05-06 17:03 UTC, christianahvilla commented on src/models/user.model.ts
> +    dataValues: any;
why is it neccesary

2022-05-06 17:03 UTC, christianahvilla commented on src/models/user.model.ts
> +User.init({
what is it?

2022-05-06 17:03 UTC, christianahvilla commented on src/models/user.model.ts
> +export default User;
```suggestion
export default User;

```

2022-05-06 17:03 UTC, christianahvilla commented on src/routes/auth.routes.ts
> +import fieldsValidation from '../middlewares/fieldsValidator';
```suggestion
import {login} from '../controllers/auth.controller';
import fieldsValidation from '../middlewares/fieldsValidator';
```

2022-05-06 17:03 UTC, christianahvilla commented on src/routes/auth.routes.ts
> +export default router;
```suggestion
export default router;

```

2022-05-06 17:03 UTC, christianahvilla commented on src/routes/user.routes.ts
> +import fieldsValidation from '../middlewares/fieldsValidator';
```suggestion
import fieldsValidation from '../middlewares/fieldsValidator';
```

2022-05-06 17:03 UTC, christianahvilla commented on src/routes/user.routes.ts
> +        res.status(201).json(user);
is it necessary?

2022-05-06 17:03 UTC, christianahvilla commented on src/server.ts
> +import dbInit from './database/init';
```suggestion
import express, { Application } from 'express';
import cors from 'cors';
import config from './config/config';
import authRoutes from './routes/auth.routes';
import userRoutes from './routes/user.routes';
import dbInit from './database/init';
```

2022-05-06 17:03 UTC, christianahvilla commented on src/server.ts
> +export default Server;
```suggestion
export default Server;

```

2022-05-06 23:31 UTC, PedroAGC commented
@christianahvilla  Fixed!

2022-05-07 00:54 UTC, christianahvilla approved these changes
LGTM

2022-05-07 00:54 UTC, christianahvilla approved these changes
LGTM

2022-05-07 00:55 UTC, christianahvilla commented
Please rebase your branch @PedroAGC

2022-05-07 01:05 UTC, merged